### ISSUE TITLE
Editing Inclusion

### ISSUE THREAD

**Issue by aroelke** [aroelke/mtg-workstation#124]
If the mana analysis tab is showing the mana analysis for a particular category, editing category inclusion causes an exception:
```
[error] Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "scala.collection.Iterable.filter(scala.Function1)" because the return value of "scala.collection.convert.AsScalaExtensions$IterableHasAsScala.asScala()" is null
[error]         at editor.gui.editor.EditorFrame.updateStats(EditorFrame.scala:1839)
[error]         at editor.gui.editor.EditorFrame.$init$$$anonfun$22(EditorFrame.scala:967)
[error]         at java.desktop/javax.swing.JComboBox.fireActionEvent(JComboBox.java:1264)
[error]         at java.desktop/javax.swing.JComboBox.contentsChanged(JComboBox.java:1337)
[error]         at java.desktop/javax.swing.JComboBox.intervalRemoved(JComboBox.java:1357)
[error]         at java.desktop/javax.swing.AbstractListModel.fireIntervalRemoved(AbstractListModel.java:188)
[error]         at java.desktop/javax.swing.DefaultComboBoxModel.removeAllElements(DefaultComboBoxModel.java:175)
[error]         at java.desktop/javax.swing.JComboBox.removeAllItems(JComboBox.java:771)
[error]         at editor.gui.editor.EditorFrame.updateCategoryPanel(EditorFrame.scala:1792)
[error]         at editor.gui.editor.EditorFrame$categories$.update$$anonfun$2(EditorFrame.scala:529)
[error]         at scala.Function0.apply$mcZ$sp(Function0.scala:39)
[error]         at editor.gui.editor.EditorFrame.performAction$$anonfun$1(EditorFrame.scala:155)
[error]         at editor.util.UndoableAction$$anon$1.redo(UndoableAction.scala:16)
[error]         at editor.gui.editor.EditorFrame.performAction(EditorFrame.scala:144)
[error]         at editor.gui.editor.EditorFrame.editor$gui$editor$EditorFrame$$performAction(EditorFrame.scala:164)
[error]         at editor.gui.editor.EditorFrame$categories$.update(EditorFrame.scala:541)
[error]         at editor.gui.editor.EditorFrame$categories$.update(EditorFrame.scala:507)
[error]         at editor.gui.editor.EditorFrame$TableCategoriesPopupListener.popupMenuWillBecomeVisible$$anonfun$4$$anonfun$1(EditorFrame.scala:620)
[error]         at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
[error]         at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
[error]         at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
[error]         at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
[error]         at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:374)
[error]         at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1022)
[error]         at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1066)
[error]         at java.desktop/java.awt.Component.processMouseEvent(Component.java:6617)
[error]         at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
[error]         at java.desktop/java.awt.Component.processEvent(Component.java:6382)
[error]         at java.desktop/java.awt.Container.processEvent(Container.java:2264)
[error]         at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4993)
[error]         at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2322)
[error]         at java.desktop/java.awt.Component.dispatchEvent(Component.java:4825)
[error]         at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4934)
[error]         at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4563)
[error]         at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4504)
[error]         at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2308)
[error]         at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
[error]         at java.desktop/java.awt.Component.dispatchEvent(Component.java:4825)
[error]         at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
[error]         at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
[error]         at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
[error]         at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
[error]         at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
[error]         at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
[error]         at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
[error]         at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
[error]         at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
[error]         at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
[error]         at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
[error]         at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
[error]         at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
[error]         at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
[error]         at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
[error]         at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
[error]         at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by aroelke** [comment]
Fixed by 63118ef.
